kind: OpenTelemetryCollector
apiVersion: opentelemetry.io/v1beta1
metadata:
  name: otlp
  namespace: netobserv
spec:
  config:
    exporters:
      debug: {}
      prometheus:
        enable_open_metrics: true
        endpoint: 0.0.0.0:8889
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      pipelines:
        logs:
          exporters:
            - debug
          receivers:
            - otlp
        metrics:
          exporters:
            - prometheus
          receivers:
            - otlp
