kind: Pod
apiVersion: v1
metadata:
  name: hello-pod-a
  namespace: test-cudn-1
  labels:
    name: hello-pod
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: "quay.io/openshifttest/hello-sdn@sha256:c89445416459e7adea9a5a416b3365ed3d74f2491beb904d61dc8d1eb89a72a4"
    name: hello-pod
    securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
---
kind: Pod
apiVersion: v1
metadata:
  name: hello-pod-b
  namespace: test-cudn-2
  labels:
    name: hello-pod
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: "quay.io/openshifttest/hello-sdn@sha256:c89445416459e7adea9a5a416b3365ed3d74f2491beb904d61dc8d1eb89a72a4"
    name: hello-pod
    securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
---
kind: Pod
apiVersion: v1
metadata:
  name: hello-pod-c
  namespace: test-udn
  labels:
    name: hello-pod
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: "quay.io/openshifttest/hello-sdn@sha256:c89445416459e7adea9a5a416b3365ed3d74f2491beb904d61dc8d1eb89a72a4"
    name: hello-pod
    securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
---
kind: Pod
apiVersion: v1
metadata:
  name: hello-pod-d
  namespace: test-udn
  labels:
    name: hello-pod
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: "quay.io/openshifttest/hello-sdn@sha256:c89445416459e7adea9a5a416b3365ed3d74f2491beb904d61dc8d1eb89a72a4"
    name: hello-pod
    securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
---
