kind: Service
apiVersion: v1
metadata:
  name: loki-microservices-query-frontend
  labels:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki-microservices
    app.kubernetes.io/version: 2.5.0
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 3100
      targetPort: http
    - name: grpc
      protocol: TCP
      port: 9095
      targetPort: grpc
    - name: grpclb
      protocol: TCP
      port: 9096
      targetPort: grpc
  internalTrafficPolicy: Cluster
  clusterIPs:
    - None
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki-microservices