{
 "title": "Clusters Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "acm_label_names",
    "label": "Label",
    "query": {
     "query": "label_values(acm_label_names, label_name)"
    }
   },
   {
    "name": "value",
    "label": "Value",
    "query": {
     "query": "label_values(acm_managed_cluster_labels, $acm_label_names)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(acm_managed_cluster_labels{$acm_label_names=~\"$value\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incoming rates",
   "type": "stat",
   "gridPos": { "h": 12, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(namespace:netobserv_workload_ingress_bytes_total:dst:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "Average"
    },
    {
     "expr": "min(sum(namespace:netobserv_workload_ingress_bytes_total:dst:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "Min"
    },
    {
     "expr": "max(sum(namespace:netobserv_workload_ingress_bytes_total:dst:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(namespace:netobserv_workload_ingress_bytes_total:dst:rate5m{cluster=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Top 10 clusters incoming traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(namespace:netobserv_workload_ingress_bytes_total:dst:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "{{cluster}} "
    }
   ]
  },
  {
   "title": "Outgoing rates",
   "type": "stat",
   "gridPos": { "h": 12, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(namespace:netobserv_workload_egress_bytes_total:src:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "Average"
    },
    {
     "expr": "min(sum(namespace:netobserv_workload_egress_bytes_total:src:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "Min"
    },
    {
     "expr": "max(sum(namespace:netobserv_workload_egress_bytes_total:src:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(namespace:netobserv_workload_egress_bytes_total:src:rate5m{cluster=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Top 10 clusters outgoing traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(namespace:netobserv_workload_egress_bytes_total:src:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "{{cluster}} "
    }
   ]
  },
  {
   "title": "Top Namespaces",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "topk(15,sum(namespace:netobserv_workload_ingress_bytes_total:dst:rate5m{cluster=~\"$cluster\"}) by (cluster,namespace) / ignoring(cluster,namespace) group_left sum(namespace:netobserv_workload_ingress_bytes_total:dst:rate5m{cluster=~\"$cluster\"}))"
    },
    {
     "expr": "topk(15,sum(namespace:netobserv_workload_egress_bytes_total:src:rate5m{cluster=~\"$cluster\"}) by (cluster,namespace) / ignoring(cluster,namespace) group_left sum(namespace:netobserv_workload_egress_bytes_total:src:rate5m{cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Cross-Cluster Traffic (cluster-ingress / cluster-egress)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Incoming rates",
   "type": "stat",
   "gridPos": { "h": 12, "w": 2, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(namespace:netobserv_workload_ingress_bytes_total:dst:unknown_src:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "Average"
    },
    {
     "expr": "min(sum(namespace:netobserv_workload_ingress_bytes_total:dst:unknown_src:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "Min"
    },
    {
     "expr": "max(sum(namespace:netobserv_workload_ingress_bytes_total:dst:unknown_src:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(namespace:netobserv_workload_ingress_bytes_total:dst:unknown_src:rate5m{cluster=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Top 10 clusters incoming traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 2, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(namespace:netobserv_workload_ingress_bytes_total:dst:unknown_src:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "{{cluster}} "
    }
   ]
  },
  {
   "title": "Outgoing rates",
   "type": "stat",
   "gridPos": { "h": 12, "w": 2, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(namespace:netobserv_workload_egress_bytes_total:src:unknown_dst:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "Average"
    },
    {
     "expr": "min(sum(namespace:netobserv_workload_egress_bytes_total:src:unknown_dst:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "Min"
    },
    {
     "expr": "max(sum(namespace:netobserv_workload_egress_bytes_total:src:unknown_dst:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(namespace:netobserv_workload_egress_bytes_total:src:unknown_dst:rate5m{cluster=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Top 10 clusters outgoing traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(namespace:netobserv_workload_egress_bytes_total:src:unknown_dst:rate5m{cluster=~\"$cluster\"}) by (cluster))",
     "legendFormat": "{{cluster}} "
    }
   ]
  }
 ]
}