{
 "title": "Per Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(acm_managed_cluster_labels{openshiftVersion_major!=\"3\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Byte Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(namespace:netobserv_workload_ingress_bytes_total:dst:rate5m{cluster=\"$cluster\",namespace!=\"\"})",
     "legendFormat": "All incoming"
    },
    {
     "expr": "sum(namespace:netobserv_workload_ingress_bytes_total:dst:unknown_src:rate5m{cluster=\"$cluster\",namespace!=\"\"})",
     "legendFormat": "Cluster incoming"
    }
   ]
  },
  {
   "title": "Top 10 namespaces - All incoming traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,namespace:netobserv_workload_ingress_bytes_total:dst:rate5m{cluster=\"$cluster\",namespace!=\"\"})",
     "legendFormat": "{{namespace}} "
    }
   ]
  },
  {
   "title": "Top 10 namespaces - Cluster-incoming traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,namespace:netobserv_workload_ingress_bytes_total:dst:unknown_src:rate5m{cluster=\"$cluster\",namespace!=\"\"})",
     "legendFormat": "{{namespace}} "
    }
   ]
  },
  {
   "title": "Packet Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(namespace:netobserv_workload_ingress_packets_total:dst:rate5m{cluster=\"$cluster\",namespace!=\"\"})",
     "legendFormat": "All incoming"
    },
    {
     "expr": "sum(namespace:netobserv_workload_ingress_packets_total:dst:unknown_src:rate5m{cluster=\"$cluster\",namespace!=\"\"})",
     "legendFormat": "Cluster incoming"
    }
   ]
  },
  { "title": "Egress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Byte Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(namespace:netobserv_workload_egress_bytes_total:src:rate5m{cluster=\"$cluster\",namespace!=\"\"})",
     "legendFormat": "All outgoing"
    },
    {
     "expr": "sum(namespace:netobserv_workload_egress_bytes_total:src:unknown_dst:rate5m{cluster=\"$cluster\",namespace!=\"\"})",
     "legendFormat": "Cluster outgoing"
    }
   ]
  },
  {
   "title": "Top 10 namespaces - All outgoing traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,namespace:netobserv_workload_egress_bytes_total:src:rate5m{cluster=\"$cluster\",namespace!=\"\"})",
     "legendFormat": "{{namespace}} "
    }
   ]
  },
  {
   "title": "Top 10 namespaces - Cluster-outgoing traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,namespace:netobserv_workload_egress_bytes_total:src:unknown_dst:rate5m{cluster=\"$cluster\",namespace!=\"\"})",
     "legendFormat": "{{namespace}} "
    }
   ]
  },
  {
   "title": "Packet Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(namespace:netobserv_workload_egress_packets_total:src:rate5m{cluster=\"$cluster\",namespace!=\"\"})",
     "legendFormat": "All outgoing"
    },
    {
     "expr": "sum(namespace:netobserv_workload_egress_packets_total:src:unknown_dst:rate5m{cluster=\"$cluster\",namespace!=\"\"})",
     "legendFormat": "Cluster outgoing"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Namespaces",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(namespace:netobserv_workload_ingress_bytes_total:dst:rate5m{cluster=\"$cluster\"}) by (namespace) / ignoring (namespace) group_left sum(namespace:netobserv_workload_ingress_bytes_total:dst:rate5m{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum(namespace:netobserv_workload_egress_bytes_total:src:rate5m{cluster=\"$cluster\"}) by (namespace) / ignoring (namespace) group_left sum(namespace:netobserv_workload_egress_bytes_total:src:rate5m{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum(namespace:netobserv_workload_ingress_bytes_total:dst:rate5m{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace:netobserv_workload_egress_bytes_total:src:rate5m{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace:netobserv_workload_ingress_bytes_total:dst:unknown_src:rate5m{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace:netobserv_workload_egress_bytes_total:src:unknown_dst:rate5m{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_owner{cluster=\"$cluster\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Top Workloads",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "topk(10,sum(workload:netobserv_workload_ingress_bytes_total:dst:rate5m{cluster=\"$cluster\",kind!=\"Node\"}) by (workload,namespace,kind)) / ignoring(namespace,workload,kind) group_left sum(workload:netobserv_workload_ingress_bytes_total:dst:rate5m{cluster=\"$cluster\"})"
    },
    {
     "expr": "topk(10,sum(workload:netobserv_workload_egress_bytes_total:src:rate5m{cluster=\"$cluster\",kind!=\"Node\"}) by (workload,namespace,kind)) / ignoring(namespace,workload,kind) group_left sum(workload:netobserv_workload_egress_bytes_total:src:rate5m{cluster=\"$cluster\"})"
    }
   ]
  }
 ]
}