kind: ConfigMap
apiVersion: v1
metadata:
  name: loki-microservices
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki-microservices
    app.kubernetes.io/version: 2.5.0
data:
  config.yaml: |
    auth_enabled: false
    common:
      storage:
        ${LOKI_STORE}
    server:
      http_listen_port: 3100
      http_server_read_timeout: 1m
      http_server_write_timeout: 1m
      grpc_server_max_recv_msg_size: 8388608
      grpc_server_max_send_msg_size: 8388608 
      log_level: error
    chunk_store_config:
      max_look_back_period: 0s
    compactor:
      compaction_interval: 5m
      shared_store: filesystem
    distributor:
      ring:
        kvstore:
          store: memberlist
    frontend:
      compress_responses: true
      log_queries_longer_than: 5s
      tail_proxy_url: http://loki-microservices-querier:3100
    frontend_worker:
      frontend_address: loki-microservices-query-frontend:9095
    ingester:
      max_chunk_age: 2h
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_idle_period: 30m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        dir: /loki-store/wal
    memberlist:
      join_members:
      - loki-microservices-memberlist
    query_range:
      parallelise_shardable_queries: true
      align_queries_with_step: true
      cache_results: true
      max_retries: 5
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_bytes: 500MB
            validity: 24h
    query_scheduler:
      max_outstanding_requests_per_tenant: 2048 
    ruler:
      alertmanager_url: https://alertmanager.xx
      external_url: https://alertmanager.xx
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      storage:
        local:
          directory: /etc/loki/rules
        type: local
    schema_config:
      configs:
        - from: 2022-01-01
          store: boltdb-shipper
          object_store: ${LOKI_STORE_NAME}
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      filesystem:
        directory: /loki-store/chunks
      boltdb_shipper:
        active_index_directory: /loki-store/index
        shared_store: filesystem
        cache_location: /loki-store/cache
        cache_ttl: 24h
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
    limits_config:    
      ingestion_rate_strategy: global 
      ingestion_rate_mb: 20
      ingestion_burst_size_mb: 40
      max_label_name_length: 1024
      max_label_value_length: 2048
      max_label_names_per_series: 30
      reject_old_samples: true
      reject_old_samples_max_age: 15m
      creation_grace_period: 10m
      enforce_metric_name: false
      max_line_size: 256000
      max_line_size_truncate: false
      max_entries_limit_per_query: 10000
      max_streams_per_user: 0
      max_global_streams_per_user: 25000
      unordered_writes: true
      max_chunks_per_query: 2000000
      max_query_length: 721h
      max_query_parallelism: 32
      max_query_series: 10000
      cardinality_limit: 100000
      max_streams_matchers_per_query: 1000
      max_concurrent_tail_requests: 10
      retention_period: 24h
      max_cache_freshness_per_query: 5m
      max_queriers_per_tenant: 0
      per_stream_rate_limit: 16MB
      per_stream_rate_limit_burst: 40MB
      max_query_lookback: 0
      min_sharding_lookback: 0s
      split_queries_by_interval: 1m
