
apiVersion: v1
kind: Secret
metadata:
  name: loki-microservices
  namespace: netobserv
type: Opaque
stringData:
  ACCESS_KEY_ID: XXXXXXXXXXXXXXXXXXXX
  SECRET_ACCESS_KEY: YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY