kind: ServiceAccount
apiVersion: v1
metadata:
  name: loki-microservices
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki-microservices
    app.kubernetes.io/version: 2.5.0
secrets:
  - name: loki-microservices
  - name: loki-microservices-token
  - name: loki-microservices-dockercfg
imagePullSecrets:
  - name: loki-microservices-dockercfg
automountServiceAccountToken: true
