apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    replicas: 3
    listeners:
      - name: tls
        port: 9092
        type: internal
        tls: true
        authentication:
          # for SASL, change to scram-sha-512
          type: tls
      - name: external
        port: 9094
        type: nodeport
        tls: true
        authentication:
          type: tls
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      auto.create.topics.enable: false
      log.cleaner.backoff.ms: 15000
      log.cleaner.dedupe.buffer.size: 134217728
      log.cleaner.enable: true
      log.cleaner.io.buffer.load.factor: 0.9
      log.cleaner.threads: 8
      log.cleanup.policy: delete
      log.retention.bytes: 107374182400
      log.retention.check.interval.ms: 300000
      log.retention.ms: 1680000
      log.roll.ms: 7200000
      log.segment.bytes: 1073741824
    metadataVersion: 4.0-IV3
    version: 4.0.0
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  entityOperator:
    topicOperator: {}
    userOperator: {}
