apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: network-flows
  labels:
    strimzi.io/cluster: "kafka-cluster"
spec:
  partitions: 24
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: informers
  labels:
    strimzi.io/cluster: "kafka-cluster"
spec:
  partitions: 24
  replicas: 1
