apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: kafka-cluster
  name: flp-kafka
spec:
  authentication:
    # for SASL, change to scram-sha-512
    type: tls
